name: C/C++ CI

on: 
  push:                 # run on push events, 
    paths-ignore:       # but ignore everything in the docs subfolder 
      - 'docs/**'      
  pull_request:         # run on pull requests,
    paths-ignore:       # but ignore everything in the docs subfolder
      - 'docs/**' 

jobs:
  
  ###########################
  # BUILDING ON WINDOWS
  ###########################
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.5.4, 3.6.8, 3.7.6, 3.8.1]
        architecture: [x86, x64]

    steps:
    
    - name: Cloning SUMO
      uses: actions/checkout@v2
      with:
        path: sumo 
      
    - name: Cloning SUMO Libraries
      uses: actions/checkout@v2
      with:
        repository: DLR-TS/SUMOLibraries 
        path: sumolibraries
    
    - name: Cloning SUMO Libraries Submodules
      run: |
        cd sumolibraries
        git submodule sync --recursive
        git submodule update --init --force --recursive --depth=1

    - name: Configuring Python 
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }} 
        architecture: ${{ matrix.architecture }}
      
    - name: Installing Python Wheel
      run: python -m pip install wheel
   
    - name: Building SUMO
      env:
        # Allow CMake build to use multiple processors (4)
        CMAKE_BUILD_PARALLEL_LEVEL: 4
      shell: cmd  # instead of PwSh (default) to be case-insensitive
      run: |
        cd sumo
        mkdir build_msvc
        cd build_msvc
        cmake .. -G"Visual Studio 16 2019" -A x64
        cmake --build . --config Release
        cd ..
      # python tools\build\setup-libsumo.py bdist_wheel
 
  ###########################
  # BUILDING ON LINUX
  ###########################
  build-linux:
    runs-on: ubuntu-latest 
    steps:
    - name: Cloning SUMO
      uses: actions/checkout@v2
   
    - name: Preparing Build System
      run: |
        sudo apt-get update 
        sudo apt-get install cmake libeigen3-dev libxerces-c-dev libfox-1.6-dev libgdal-dev libproj-dev libgtest-dev libgl2ps-dev python3-dev swig openjdk-8-jdk maven
    
    - name: Preparing Gtest
      run: |
        pushd /usr/src/gtest
        sudo mkdir build
        cd build
        sudo cmake ..
        sudo make
        sudo cp libgtest* /usr/lib/
    
    - name: Building SUMO
      run: |
        mkdir cmake-build 
        cd cmake-build 
        cmake .. 
        make -j4

    - name: Building Traas
      run: |
        cd cmake-build 
        make traas
      
    - name: Installing SUMO
      run: |
        cd cmake-build 
        sudo make install
      
    - name: Building Examples and Tests
      run: |
        cd cmake-build
        make CTEST_OUTPUT_ON_FAILURE=1 examples test

  ###################
  # BUILDING ON OSX
  ###################
  build-osx:
    runs-on: macos-latest
    steps:
    - name: Cloning SUMO
      uses: actions/checkout@v2
   
    - name: Preparing Build System
      run: |
        brew update
        brew cask install xquartz
        brew install xerces-c fox proj gdal gl2ps  
   
    - name: Installing Google Test
      run: |
        git clone https://github.com/google/googletest
        cd googletest
        mkdir build
        cd build
        cmake ..
        make
        make install  
        
    - name: Building SUMO
      run: |
        mkdir cmake-build 
        cd cmake-build 
        cmake .. 
        make -j4

    - name: Building Traas
      run: |
        cd cmake-build 
        make traas
      
    - name: Installing SUMO
      run: |
        cd cmake-build 
        sudo make install
    
    - name: Building Examples and Tests
      run: |
        cd cmake-build
        make CTEST_OUTPUT_ON_FAILURE=1 examples test
     
